### PR TITLE
Move the seeders into test directory

### LINKED ISSUE #471: Move Seeders Into Tests Directory?
Since the seeders are made for the tests we should probably move them into the tests directory. What do you think about this @lucadegasperi ?

### PR DESCRIPTION
**Pull request by vinkla**
Also renamed the DatabaseSeeder to OAuth2DatabaseSeeder.

This closes #471, #467 and #435.

### CODE REVIEW

**Comment by vinkla** [comment]
The tests seem to fail, works fine locally. Any idea @lucadegasperi ?

**Comment by lucadegasperi** [comment]
Just travis acting weirdly.

**Comment by vinkla** [comment]
:+1:

**Comment by lukasoppermann** [comment]
When will this be released? Could you do it now? Every time I update composer in my lumen project I get all the yellow stuff. :)

**Comment by vinkla** [comment]
@lukasoppermann you can test this by updating the version number for this package to `5.0.*@dev`.

**Pull request merged**
