### PR TITLE
fix #322 vendor:publish command for migrations

### LINKED ISSUE #322: Laravel 5 bypasses "before" =>"OAuth"
In my routes file, I have the following:

/**
 * Secured Endpoints
 */
Route::group(['before' => 'OAuth'], function () {
    /**
     * categories Block
     */
    Route::get("categories", [
        "as" => "categories/index",
        "uses" => "CategoriesController@index"
    ]);
});

I've implemented everything in your package as directed in the wiki, but even if I don't provide a token, this end point will work.

Is there Middleware object I need to configure, create, or could it be something else?

### LINKED ISSUE #332: vendor:publish always copy migrations to database/migrations
When i add new package to composer then using `vendor:publish`, the new migrations were created. This causes troubles with `composer dumpautoload` and `migrate` commands.

### PR DESCRIPTION
**Pull request by yajra**
PR to fix #332

### CODE REVIEW

**Comment by lucadegasperi** [comment]
The migrations need to run in order, having them added with the timestamp at the time they were created  is wrong.

**Comment by yajra** [comment]
I see then we need to rename the files. We should not add timestamps dynamically because it will cause the files to copied every publish command.

**Comment by lucadegasperi** [comment]
Every file should be checked for existence before being moved i guess.

**Comment by yajra** [comment]
Yes, but Laravel automatically checks the file and will not copy if it does exists.

**Comment by tpavlek** [comment]
Any possibility of this being merged? It's a pretty frustrating issue.

**Comment by jenky** [comment]
I see you have your own command `php artisan oauth2-server:create-client`. Why not create your own migration command instead of using `vendor:publish`, something like `php artisan oauth2-server:migrate`

**Comment by lucadegasperi** [comment]
That command is going to be deprecated. I will see what i can do.

**Comment by lucadegasperi** [comment]
No longer actual.

**Pull request closed without merging**
