### PR TITLE
[fix issue #679]miss a situation in function get

### PR DESCRIPTION
**Pull request by Manasseh-Zhou**
if (is_null($redirectUri) && is_null($clientSecret))
@vinkla

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for your contribution!

@lucadegasperi could you please check this. It is related to #679

**Comment by Manasseh-Zhou** [comment]
why not make the redirectUri gettable in these situations?

**Comment by Manasseh-Zhou** [comment]
Havn't checked yet?

**Comment by vinkla** [comment]
Thanks for your pull request but this package should now be considered deprecated in favour of [Laravel Passport](https://laravel.com/docs/5.3/passport).

**Pull request closed without merging**
