### PR TITLE
Add Laravel 5.1 support on and update branch alias to 4.1

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by lucadegasperi** [comment]
Tests aren't passing, once they do, I'll merge this :)

**Comment by vinkla** [comment]
Yeah, sorry about that. Added this directly on GitHub in quite a haste. The tests should pass now :)

**Comment by vinkla** [comment]
The Scruitinizer returns the following;

````
Installing vendors through composer ...
+===================================================================================+
| You can avoid this step by committing your composer.lock file to your repository. |
+===================================================================================+
```

The Travis seems to pass though.

**Comment by vinkla** [comment]
The tests are now passing :)

**Comment by finalight** [comment]
are there any guides for install this package on laravel 5.1, or is it the same?

i notice that there might have some changes that we need to made for middle ware

**Comment by lucadegasperi** [comment]
It should work as it is right now but it isn't optimized to take advantage of the new L5.1 feature, working on it though.

**Comment by finalight** [comment]
ok thanks, i think i will wait for it though haha

**Pull request merged**
