### PR TITLE
Add compatibility with mongodb storage

### PR DESCRIPTION
**Pull request by swaaj**
I have modified storage classes and added database queries that are compatible with mongodb databases.
After making the changes, I have run <code>phpunit</code> and passed all the tests.

### CODE REVIEW

**Comment by lucadegasperi** [comment]
Man, this looks ugly. Why don't you implement the storage interfaces specifically for mongo and make a package out of them?

**Comment by swaaj** [comment]
Okay, I have implemented storage interfaces specifically for mongo now. And they can be used by using <code>'LucaDegasperi\OAuth2Server\Storage\Mongo\FluentStorageServiceProvider'</code> instead of <code>'LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider'</code> in app/config.php.

**Comment by gauravdave01** [comment]
When are you going to merge that Mongo compatible code in your package?

**Comment by lucadegasperi** [comment]
This pull request is too dirty and it should be based on the newer version of the package storage interfaces if you want me to merge it.

**Comment by gauravdave01** [comment]
Ok, No Issues!

**Pull request closed without merging**
