### PR TITLE
Add better PSR-2 support

### LINKED ISSUE #475: Better PSR-2 Support
Would you accept an pull request for better PSR-2 support? Maybe adding PHP CS Fixer file?

### PR DESCRIPTION
**Pull request by vinkla**
Also update the license information and added description to all classes.

Also added `.php_cs` and `.styleci.yml` files. [StyleCI](https://styleci.io/) will check syntax on all PRs and commits done to this repository. @lucadegasperi What do you think about this? Personally I use StyleCI on all my packages. It saves me a lot of time telling people to correct their PRs. 

This closes #475.

### CODE REVIEW

**Comment by vinkla** [comment]
Seems there is something up with Travis? Maybe this has something to do with #419?

**Comment by lucadegasperi** [comment]
It has problems in general lately. Guess it is due to the configuration being used.

**Comment by vinkla** [comment]
We should try fixing it. I'll try to push a fix when I have time to spare. What about this PR can we merge it?

**Comment by vinkla** [comment]
What about this PR can we merge it?

**Comment by vinkla** [comment]
Great! Don't forget to register the repo at https://styleci.io/

**Pull request merged**
