### PR TITLE
Mac token support

### PR DESCRIPTION
**Pull request by joaopramos**
Added mac token support.

### CODE REVIEW

**Comment by vinkla** [comment]
Please try to cleanup the commit history and [squash your commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) before we take a look on this.

**Comment by joaopramos** [comment]
I now squashed the commits.

**Comment by olezko46** [comment]
:+1:

**Comment by vinkla** [comment]
@joaopramos please add tests for this.

**Comment by vinkla** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
