### PR TITLE
Update readme for Laravel 5.1

### PR DESCRIPTION
**Pull request by robinvalk**
Required php version changed to 5.5.9
(http://laravel.com/docs/5.1/installation#installation)

### CODE REVIEW

**Comment by vinkla** [comment]
We also need to update the `composer.json` with the new PHP version. Currently it doesn't support Laravel 5.1 yet.

**Comment by robinvalk** [comment]
Ah yeah I missed that. Also the wiki etc can be updated to use  `::class` now the higher php version is required.

**Comment by robinvalk** [comment]
Created an issue for the convenience: #415

**Comment by vinkla** [comment]
:+1:

**Comment by lucadegasperi** [comment]
Agree with all of you. I'm already working on the middleware with parameters.

**Pull request closed without merging**
