### PR TITLE
Update branch aliases

### PR DESCRIPTION
**Pull request by vinkla**
Since next version will be breaking we need to set it to 5.0

### CODE REVIEW

**Comment by lucadegasperi** [comment]
I think the changes we made are not that breaking and thus I would like to release these changes as 4.1. What's your opinion on it @vinkla ?

**Comment by vinkla** [comment]
I think pushing `5.0` is a good idea. Lets say developers use the old filters and specifies `~4.0` as version in their composer files. When we push a new version their code could break. I think it would be better if we pushed this version as `5.0`. Less people getting confused why their code doesn't work anymore.

**Comment by lucadegasperi** [comment]
Sounds good to me. Let's merge it.

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
