### PR TITLE
Array to Object Conversion

### PR DESCRIPTION
**Pull request by SArnab**
We were facing issues with the assumed fetch mode of the storage adapters. Rather than try to fight it, we found the simplest solution was to type-cast the array to an object.

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for your contribution. Please cleanup your commit history and then we take a look.

**Comment by SArnab** [comment]
@vinkla I'm not entirely sure how to go about this using rebase. The initial change was made on a separate branch, merged into master, after which the the style fixes were applied. The relevant commits are fe24216 and 22f3b09.

**Comment by vinkla** [comment]
Maybe try closing this and do the PR from scratch opening a new one?

**Comment by vinkla** [comment]
We've discussed this internally and we've decided to not go further with this. Thanks for your suggestion.

**Pull request closed without merging**
