### PR TITLE
Added New Middleware

### PR DESCRIPTION
**Pull request by vinkla**
Added OAuthUserMiddleware and OAuthClientMiddleware.

### CODE REVIEW

**Comment by lucadegasperi** [comment]
not sure about the naming, we're still talking about token ownership and that's important to remember.

**Comment by vinkla** [comment]
Thats true, what about OAuthUserOwnerMiddleware and OAuthClientOwnerMiddleware?

**Comment by lucadegasperi** [comment]
:+1:

**Comment by vinkla** [comment]
Done. Turning green.

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
