### PR TITLE
Patch 4

### PR DESCRIPTION
**Pull request by od3n**

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for your pull requests but this is just a syntax update right?

**Comment by vinkla** [comment]
Doesn't change behaviour?

**Comment by od3n** [comment]
@vinkla yes and no.

**Comment by vinkla** [comment]
@od3n please describe why we should merge this.

**Comment by vinkla** [comment]
Thanks for your pull request but this package should now be considered deprecated.

**Pull request closed without merging**
