### PR TITLE
Update ignore file and removed phpspec.yml and phpunit.xml

### PR DESCRIPTION
**Pull request by vinkla**
We should only save the distribution versions.

### CODE REVIEW

**Comment by lucadegasperi** [comment]
I use the other ones on my local machine as I don't need reporting and stuff there.

**Comment by vinkla** [comment]
Yeah, thats good. How we are supposed to work. Though, its common to not commit them. Since they are custom for each developer.

**Comment by vinkla** [comment]
Any update on this?

**Comment by lucadegasperi** [comment]
Getting back to this one soon.

**Comment by vinkla** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
> I use the other ones on my local machine as I don't need reporting and stuff there.

They belong in a global ignore file.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by vinkla** [comment]
Fixed in #480

**Pull request closed without merging**
