### PR TITLE
fixing CONTRIBUTING.md typo. changing migration destination prefix 

### PR DESCRIPTION
**Pull request by mathiasgrimm**
No migration files will be prefixed with current date instead of that static date (2015_01_01_*)
Source migration files renamed as well to _0000**_*

### CODE REVIEW

**Comment by mathiasgrimm** [comment]
the reason I did this is because when i migrated from laravel 4 to laravel 5 I had to migrate this package as well. So I created migrations to drop the old oauth tables and and installed the new package from scratch. When I published the vendor the migrations got a date prior to my migrations and than when I tried to migrate migrations failed because tried to create the tables before my drop tables.

**Comment by mathiasgrimm** [comment]
actually there is a problem yet. will fix and send it again

**Comment by vinkla** [comment]
Could you split these two fixes into separate PRs? Though, I don't agree we should rename the migrations. We handle this the same way Laravel does https://github.com/laravel/laravel/tree/master/database/migrations

**Comment by mathiasgrimm** [comment]
Will split.

To be honest I don't think the way laravel does is the best way.

In the case of Oauth I had to rename manually 14 files, nobody deserves this, specially when the laravel ecosystem dictates that programming should be a pleasure.

There is no harm in this approach and sort some edge cases as well.

Could you point any cons?

**Comment by mathiasgrimm** [comment]
ready to go!!

**Comment by mathiasgrimm** [comment]
the typo fix is in another PR that i submitted, and is in this PR as well, should be no problem

**Comment by lucadegasperi** [comment]
This already changed on the develop branch

**Comment by mathiasgrimm** [comment]
But doest not solve the problem.

All the migrations will likely be executed before any other migration.
In my case I migrated from L4 to L5 and had to drop all oauth tables so I had a migration
2015_06_05_123143_delete_oauth_tables.php
and all the oauth migrations were 2015_01_01_* which the `php artisan migrate` tried to execute before my migration and therefore caused lots of problems because the tables existed.

My PR solves completely this problem and gives a name based on the migration pattern which is  date('Y_m_d_His');

By doing this people don't have to be concerned about the migrations order/name anymore.
Plug and Play!

**Comment by vinkla** [comment]
I can see the problem when upgrading. Though, we can't support everyones setup. We publish the migrations as specified in the [Laravel documentation](http://laravel.com/docs/5.1/packages#publishing-file-groups).

**Comment by mathiasgrimm** [comment]
Ok, will send the PR firs to laravel.
Thanks

**Comment by vinkla** [comment]
Yeah, this should definitely be a feature in Laravel. Setting the date when publishing migrations. Let me know how it goes and if I could help in any way!

**Comment by mathiasgrimm** [comment]
https://github.com/laravel/framework/issues/9232

**Comment by vinkla** [comment]
Maybe you could simplify the description in that issue. I know Taylor has a lot on his plate and if we could only describe the feature in a couple of lines it would be more likely to be considered!

Something like; prepend date to migrations during package publish or something similar.

**Comment by mathiasgrimm** [comment]
ok

**Pull request closed without merging**
