### PR TITLE
Update to new L5 way of publishing assets

### PR DESCRIPTION
**Pull request by HipsterJazzbo**
This PR combined with #211 should get this package more or less ready for L5.

### CODE REVIEW

**Comment by lucadegasperi** [comment]
Thanks. There's still a problem with migration that when copied preserve the timestamp they have and which might cause problems with migrations that should run before this ones.

**Comment by HipsterJazzbo** [comment]
Yeah. After some research, I think the only way to do this is to list each migration file individually in `publishes()` and publish them each with the datestamp prepended:

```php
$this->publishes([
    ...
    $migrationsDir.$migrationFilename => $this->app['path.database'].'/migrations/'.date('Y_m_d_His').'_'.$migrationFilename,
    ...
]);
```

If that acceptable to you (but obviously a bit cleaner with a loop and stuff), I'll get it done today.

**Comment by lucadegasperi** [comment]
There still a problem with migrations published in a row which would have the same timestamp, thus not preserving the order of this ones. I'll proceed implementing the changes on the weekend. So we should have a L5 "ready" package fairly soon.

**Comment by lucadegasperi** [comment]
I've taken inspiration from this and rolled my own implementation. Thanks for contributing!

**Pull request closed without merging**
